# Generated by Django 6.0.6 on 2026-07-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0005_remove_statement_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_vendor', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('deterministic', 'Deterministic'), ('ai', 'AI')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
